name = "testy-cool"
pages_build_output_dir = "apps/web/out"

[vars]
LANGFUSE_PUBLIC_KEY = "pk-lf-3bb9c1ff-043b-4810-9ea7-174350b836d3"
LANGFUSE_BASE_URL = "https://langfuse-f6tim406p7bpze5wutvcm4jv.voidxd.cloud"
WINDMILL_BASE_URL = "https://windmill.voidxd.cloud"
WINDMILL_WORKSPACE = "main"
WINDMILL_FLOW_PATH = "u/vlad/video_breakdown"

[[kv_namespaces]]
binding = "PANTRY_CACHE"
id = "a32dc72386f24bb793f88b9f96777b40"
