import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const targetDir = path.resolve(__dirname, "../data");
const targetFile = path.resolve(targetDir, "models-snapshot.ts");

const OPENROUTER_PROVIDER_MAP = {
  anthropic: "anthropic",
  openai: "openai",
  google: "google",
  deepseek: "deepseek",
  "x-ai": "xai",
  mistralai: "mistral",
  "meta-llama": "meta",
  meta: "meta",
  qwen: "qwen",
  amazon: "amazon",
  cohere: "cohere",
  "z-ai": "zhipu",
  zhipu: "zhipu",
  xiaomi: "xiaomi",
};

function cleanModelName(rawName, id) {
  const [, slug] = id.split("/");
  const base = (rawName || slug || id).trim();
  return base
    .replace(
      /^(Anthropic|OpenAI|Google|DeepSeek|SpaceXAI|xAI|Mistral|Meta|Qwen|Amazon|Cohere|Z\.ai|Xiaomi):\s*/i,
      ""
    )
    .trim();
}

async function syncModels() {
  console.log("Fetching latest models from OpenRouter API...");
  const res = await fetch("https://openrouter.ai/api/v1/models");
  if (!res.ok) {
    throw new Error(`Failed to fetch OpenRouter models: ${res.status} ${res.statusText}`);
  }

  const json = await res.json();
  const rawList = json.data;
  console.log(`Received ${rawList.length} raw models from OpenRouter.`);

  const datePattern = /(-\d{4}-\d{2}-\d{2}|-\d{8}|-\d{4,6}$)/;
  const candidateModels = [];

  for (const m of rawList) {
    const id = m.id;
    if (!id || id.includes(":batch") || id.includes(":free")) continue;
    const parts = id.split("/");
    if (parts.length !== 2) continue;
    const [pRaw, slug] = parts;
    const provider = OPENROUTER_PROVIDER_MAP[pRaw];
    if (!provider) continue;

    candidateModels.push({ id, slug, provider, raw: m });
  }

  const slugSet = new Set(candidateModels.map((c) => c.slug));
  const deduped = [];

  for (const c of candidateModels) {
    const match = datePattern.exec(c.slug);
    if (match) {
      const baseSlug = c.slug.slice(0, match.index);
      if (slugSet.has(baseSlug)) {
        continue;
      }
    }
    deduped.push(c);
  }

  // Sort newest models first by creation date
  deduped.sort((a, b) => (b.raw.created || 0) - (a.raw.created || 0));

  const result = [];

  for (const { id, slug, provider, raw } of deduped) {
    const pricing = raw.pricing || {};
    const input = Math.round(parseFloat(pricing.prompt || "0") * 1_000_000 * 10000) / 10000;
    const output = Math.round(parseFloat(pricing.completion || "0") * 1_000_000 * 10000) / 10000;

    if (input === 0 && output === 0) continue;

    let cachedInput = input;
    if (pricing.input_cache_read !== undefined && pricing.input_cache_read !== null) {
      cachedInput =
        Math.round(parseFloat(pricing.input_cache_read || "0") * 1_000_000 * 10000) / 10000;
    }

    let reasoning = undefined;
    if (
      pricing.internal_reasoning !== undefined &&
      pricing.internal_reasoning !== null &&
      parseFloat(pricing.internal_reasoning) > 0
    ) {
      reasoning =
        Math.round(parseFloat(pricing.internal_reasoning) * 1_000_000 * 10000) / 10000;
    } else if (
      provider === "anthropic" ||
      /\b(o1|o3|o4|thinking|reasoner|sol)\b/i.test(slug) ||
      /\b(o1|o3|o4)\b/i.test(raw.name || "")
    ) {
      reasoning = output;
    }

    const top = raw.top_provider || {};
    const context = raw.context_length || top.context_length || 128_000;
    const maxOutput = top.max_completion_tokens || 4096;

    const rawMods = raw.architecture?.input_modalities || ["text"];
    const modalities = [];
    for (const m of rawMods) {
      if (m === "text" || m === "image" || m === "audio" || m === "video") {
        if (!modalities.includes(m)) modalities.push(m);
      } else if (m === "file" || m === "pdf") {
        if (!modalities.includes("pdf")) modalities.push("pdf");
      }
    }
    if (modalities.length === 0) modalities.push("text");

    const name = cleanModelName(raw.name || slug, id);

    result.push({
      id,
      name,
      provider,
      input,
      output,
      cachedInput,
      context,
      maxOutput,
      modalities,
      ...(reasoning !== undefined ? { reasoning } : {}),
      created: raw.created,
    });
  }

  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
  }

  const fileContent = `// Auto-generated by scripts/sync-models.mjs
// Do not edit manually. Synced from OpenRouter API on ${new Date().toISOString()}

import type { Model } from "@/lib/llm-models";

export const modelsSnapshot: Model[] = ${JSON.stringify(result, null, 2)};
`;

  fs.writeFileSync(targetFile, fileContent, "utf-8");
  console.log(`Successfully wrote ${result.length} models to ${targetFile}`);
}

syncModels().catch((err) => {
  console.error("Sync error:", err);
  process.exit(1);
});
